### ISSUE TITLE
Release with ppxlib compatibility

### ISSUE THREAD

**Issue by pitag-ha** [zepalmer/ocaml-monadic#11]
Now that the main branch is compatible with ppxlib, it would be great  if it could be released so that we have a ppxlib compatible version.

**Comment by pitag-ha** [comment]
I'm sorry for this. I've just seen that it's already released on opam (I just had a quick look on github). Thanks for that!

**Comment by zepalmer** [comment]
:+1: Thanks for all of your guidance in migration.  :)
