### ISSUE TITLE
[%guard] is not processed if it appears before an extension

### ISSUE THREAD

**Issue by zepalmer** [zepalmer/ocaml-monadic#4]
The following code results in an unprocessed guard:

```ocaml
[%guard some_condition];
let%bind x = some_expr in
some_other_expr
```

**Comment by hcarty** [comment]
Do you have more complete code?  A simple example works here:

```ocaml
let bind x f =
  match x with
  | None -> None
  | Some x -> f x

let zero () = None

let test cond =
  let result =
    [%guard cond];
    let%bind y = Some "hello" in
    Some y
  in
  match result with
  | None -> print_endline "None"
  | Some _ -> print_endline "Some"

let () =
  test true;
  test false
```

This prints `Some` then `None` as I would expect.  Tested with 0.3.3 and OCaml 4.04.0.

**Comment by zepalmer** [comment]
It seems I was wrong and this is a red herring.  The actual code I was working with was something like this:

```ocaml
Nondeterminism_monad.enum @@
[%guard some_condition];
let%bind item = pick_enum @@ some_enumeration in
return @@ operation item
```

For those who may suffer the same fate as I: the ";" operator in OCaml has too low precedence and so the above is parsed like

```ocaml
(
    Nondeterminism_monad.enum @@
    [%guard some_condition]
);
let%bind item = pick_enum @@ some_enumeration in
return @@ operation item
```

which is not what I had intended.  In the above case, though, it'd be good to get a better error message.  I'll open a bug for that instead.
